# Generated by Django 4.0 on 2021-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_assigned_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
    ]
